name: ArXiv hep-th daily

on:
  schedule:
    # 06:00 UTC covers 08:00 during summer (CEST=UTC+2)
    - cron: "0 6 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: arxiv-hepth-bot
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Ensure run time is 08:00 in Europe/Berlin
        run: |
          HOUR=$(TZ=Europe/Berlin date +%H)
          if [ "$HOUR" != "08" ]; then
            echo "Not 08:00 Europe/Berlin (now $HOUR) — skipping."
            exit 0
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Arxiv-Bot-for-hepth/requirements.txt

      - name: Post today’s New submissions
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python Arxiv-Bot-for-hepth/Arxiv_bot.py --once --chat "${TELEGRAM_CHAT_ID}"
