name: ArXiv hep-th daily

on:
  schedule:
    # 06:00 UTC covers 08:00 during summer (CEST=UTC+2)
    - cron: "0 5 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: arxiv-hepth-bot
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Skip weekends (Europe/Berlin)
        id: skip_weekend
        run: |
          DOW=$(TZ=Europe/Berlin date +%u)
          if [ "$DOW" -ge 6 ]; then
            echo "Today is weekend (Sat/Sun in Europe/Berlin). Skipping run."
            exit 0
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Restore posted state
        uses: actions/cache/restore@v4
        with:
          path: Arxiv-Bot-for-hepth/.state
          key: arxiv-state-${{ github.run_id }}
          restore-keys: |
            arxiv-state-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Arxiv-Bot-for-hepth/requirements.txt

      - name: Post today’s New submissions
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FORCE_POST: ${{ github.event_name == 'workflow_dispatch' && '1' || '0' }}
        run: |
          python Arxiv-Bot-for-hepth/Arxiv_bot.py --once --chat "${TELEGRAM_CHAT_ID}"

      - name: Save posted state
        if: always()
        uses: actions/cache/save@v4
        with:
          path: Arxiv-Bot-for-hepth/.state
          key: arxiv-state-${{ github.run_id }}
          if-no-files-found: ignore
